# Generated by Django 5.1.5 on 2026-04-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
