# Generated by Django 5.1.5 on 2026-04-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0002_profile_image_to_textfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadhistory',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
