# Generated by Django 5.1.5 on 2025-01-18 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
