# Generated by Django 5.1.5 on 2025-01-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0004_alter_userprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
