# Generated by Django 5.1.5 on 2025-01-22 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0012_passwordhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordHistory',
        ),
    ]
