# Generated by Django 5.1.5 on 2025-01-29 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0014_userprofile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
    ]
