# Generated by Django 5.1.5 on 2025-01-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0015_remove_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=10),
        ),
    ]
