# Generated by Django 5.1.5 on 2025-02-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0017_helpmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpmessage',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='helpmessage',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
