# Generated by Django 5.1.5 on 2025-02-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0020_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default='default1.jpg', upload_to='profile_pics/'),
        ),
    ]
