# Generated by Django 5.1.5 on 2025-02-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0022_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
