# Generated by Django 5.1.5 on 2025-02-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0026_userprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
