# Generated by Django 5.1.5 on 2025-02-14 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0029_userprofile_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_staff',
        ),
    ]
