# Generated by Django 5.1.5 on 2025-02-16 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0031_processedvideo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProcessedVideo',
        ),
    ]
